### ISSUE TITLE
"Unfortunately, PhotoCloud Slideshow has stopped" at launch on Galaxy Tab 2 7", GT-P3110.

### ISSUE THREAD

**Issue by asktoby** [mvysny/photocloud-frame-slideshow#177]
Hello,

PhotoCloud used to work great on my device but at some point around a year ago it stopped working.
Now, when I tap the icon, I see the window appear for a second before disappearing with the dialog:

Unfortunately, PhotoCloud Slideshow has stopped.
[Report] [OK]

I have pressed [Report] to submit the issue.

**Comment by mvysny** [comment]
Hi, thank you for reporting the issue. Unfortunately I can see no crash report in Google Play Console for any Samsung or any Galaxy Tab. Is your device online please? If it is, what is the Android version please?

Would you be open to attaching your device to your computer and retrieving the crash? You can try following https://www.android-photo-frame.eu/faq.html the "Reporting crashes"

**Comment by asktoby** [comment]
```
2022-09-16 11:53:07.779   660-660   Timeline                com.cyanogenmod.trebuchet            I  Timeline: Activity_launch_request id:sk.baka.photoframe time:876342523
2022-09-16 11:53:07.779   117-8759  AudioPolicyManagerBase  pid-117                              D  getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
2022-09-16 11:53:07.779   117-8759  AudioPolicyManagerBase  pid-117                              D  getOutput() returns output 2
2022-09-16 11:53:07.779   117-117   AudioPolicyManagerBase  pid-117                              D  getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
2022-09-16 11:53:07.779   117-117   AudioPolicyManagerBase  pid-117                              D  getOutput() returns output 2
2022-09-16 11:53:07.779   117-272   AudioPolicyManagerBase  pid-117                              D  getOutput() device 2, stream 1, samplingRate 48000, format 1, channelMask 3, flags 4
2022-09-16 11:53:07.779   117-272   AudioPolicyManagerBase  pid-117                              D  getOutput() returns output 2
2022-09-16 11:53:07.779   427-488   AudioTrack              system_process                       W  AUDIO_OUTPUT_FLAG_FAST denied by client due to mismatching sample rate (48000 vs 44100)
2022-09-16 11:53:07.779   117-8759  AudioFlinger            pid-117                              D  start(4100), calling pid 427 session 107
2022-09-16 11:53:07.779   117-8759  AudioFlinger            pid-117                              D  ? => ACTIVE (4100) on thread 0x4124bc20
2022-09-16 11:53:07.779   117-8759  AudioPolicyManagerBase  pid-117                              D  startOutput() output 2, stream 1, session 107
2022-09-16 11:53:07.779   427-849   ActivityManager         system_process                       I  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=sk.baka.photoframe cmp=sk.baka.photoframe/.MainActivity bnds=[80,340][253,443]} from pid 660
2022-09-16 11:53:07.786   117-270   audio_hw_primary        pid-117                              D  select_output_device: AUDIO_DEVICE_OUT_SPEAKER
2022-09-16 11:53:07.810   427-444   BroadcastQueue          system_process                       W  Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.cyanogenmod.trebuchet (uid 10013)
2022-09-16 11:53:07.888 23465-23465 Zygote                  pid-23465                            V  Switching descriptor 33 to /dev/null
2022-09-16 11:53:07.888 23465-23465 Zygote                  pid-23465                            V  Switching descriptor 9 to /dev/null
2022-09-16 11:53:07.896   427-1964  ActivityManager         system_process                       I  Start proc sk.baka.photoframe for activity sk.baka.photoframe/.MainActivity: pid=23465 uid=10062 gids={50062, 3003, 1028, 1015}
2022-09-16 11:53:08.013 23465-23465 ActivityThread          pid-23465                            D  handleBindApplication:sk.baka.photoframe
2022-09-16 11:53:08.013 23465-23465 ActivityThread          sk.baka.photoframe                   D  setTargetHeapUtilization:0.75
2022-09-16 11:53:08.013 23465-23465 ActivityThread          sk.baka.photoframe                   D  setTargetHeapMinFree:524288
2022-09-16 11:53:08.052 23465-23465 dalvikvm                sk.baka.photoframe                   I  Could not find method android.net.ConnectivityManager.getAllNetworks, referenced from method sk.baka.photoframe.App.isConnectedViaUnmetered
2022-09-16 11:53:08.052 23465-23465 dalvikvm                sk.baka.photoframe                   W  VFY: unable to resolve virtual method 1846: Landroid/net/ConnectivityManager;.getAllNetworks ()[Landroid/net/Network;
2022-09-16 11:53:08.052 23465-23465 dalvikvm                sk.baka.photoframe                   D  VFY: replacing opcode 0x6e at 0x0054
2022-09-16 11:53:08.076 23465-23465 MultiDex                sk.baka.photoframe                   I  VM with version 1.6.0 does not have multidex support
2022-09-16 11:53:08.076 23465-23465 MultiDex                sk.baka.photoframe                   I  Installing application
2022-09-16 11:53:08.076 23465-23465 MultiDex                sk.baka.photoframe                   I  MultiDexExtractor(/data/app/sk.baka.photoframe-1.apk, /data/data/sk.baka.photoframe/code_cache/secondary-dexes)
2022-09-16 11:53:08.076 23465-23465 MultiDex                sk.baka.photoframe                   I  Blocking on lock /data/data/sk.baka.photoframe/code_cache/secondary-dexes/MultiDex.lock
2022-09-16 11:53:08.076 23465-23465 MultiDex                sk.baka.photoframe                   I  /data/data/sk.baka.photoframe/code_cache/secondary-dexes/MultiDex.lock locked
2022-09-16 11:53:08.076 23465-23465 MultiDex                sk.baka.photoframe                   I  MultiDexExtractor.load(/data/app/sk.baka.photoframe-1.apk, false, )
2022-09-16 11:53:08.083 23465-23465 MultiDex                sk.baka.photoframe                   I  loading existing secondary dex files
2022-09-16 11:53:08.083 23465-23465 MultiDex                sk.baka.photoframe                   I  load found 2 secondary dex files
2022-09-16 11:53:08.091 23465-23465 MultiDex                sk.baka.photoframe                   I  install done
2022-09-16 11:53:08.091 23465-23465 dalvikvm                sk.baka.photoframe                   I  Could not find method android.content.Context.getExternalMediaDirs, referenced from method android.support.v4.content.FileProvider.parsePathStrategy
2022-09-16 11:53:08.091 23465-23465 dalvikvm                sk.baka.photoframe                   W  VFY: unable to resolve virtual method 795: Landroid/content/Context;.getExternalMediaDirs ()[Ljava/io/File;
2022-09-16 11:53:08.091 23465-23465 dalvikvm                sk.baka.photoframe                   D  VFY: replacing opcode 0x6e at 0x009b
2022-09-16 11:53:08.115 23465-23465 sk.baka.photoframe.App  sk.baka.photoframe                   I  Preparing /storage/emulated/0/Android/data/sk.baka.photoframe/files/tmp_download: deleting recursively and mkdiring
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   I  Could not find method java.io.File.toPath, referenced from method sk.baka.android.spi.Java7FS.delete
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   W  VFY: unable to resolve virtual method 1303: Ljava/io/File;.toPath ()Ljava/nio/file/Path;
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   D  VFY: replacing opcode 0x6e at 0x0002
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   W  VFY: unable to resolve exception class 806 (Ljava/nio/file/DirectoryNotEmptyException;)
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   W  VFY: unable to find exception handler at addr 0x2c
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   W  VFY:  rejected Lsk/baka/android/spi/Java7FS;.delete (Ljava/io/File;)V
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   W  VFY:  rejecting opcode 0x0d at 0x002c
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   W  VFY:  rejected Lsk/baka/android/spi/Java7FS;.delete (Ljava/io/File;)V
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   W  Verifier rejected class Lsk/baka/android/spi/Java7FS;
2022-09-16 11:53:08.122 23465-23465 AndroidRuntime          sk.baka.photoframe                   D  Shutting down VM
2022-09-16 11:53:08.122 23465-23465 dalvikvm                sk.baka.photoframe                   W  threadid=1: thread exiting with uncaught exception (group=0x418c1ce0)
2022-09-16 11:53:08.122 23465-23465 AndroidRuntime          sk.baka.photoframe                   E  FATAL EXCEPTION: main
                                                                                                    Process: sk.baka.photoframe, PID: 23465
                                                                                                    java.lang.VerifyError: sk/baka/android/spi/Java7FS
                                                                                                    	at sk.baka.android.DirUtils.get(DirUtils.java:303)
                                                                                                    	at sk.baka.android.DirUtils.deleteNonRec(DirUtils.java:119)
                                                                                                    	at sk.baka.android.DirUtils.deleteRecursively(DirUtils.java:152)
                                                                                                    	at sk.baka.android.DirUtils.deleteRecursively(DirUtils.java:129)
                                                                                                    	at sk.baka.android.DirUtils.deleteRecursively(DirUtils.java:148)
                                                                                                    	at sk.baka.android.DirUtils.deleteRecursivelyQuietly(DirUtils.java:267)
                                                                                                    	at sk.baka.photoframe.App.prepareTemp(App.java:510)
                                                                                                    	at sk.baka.photoframe.App.onCreate(App.java:108)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:136)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:5146)
                                                                                                    	at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                    	at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
                                                                                                    	at dalvik.system.NativeStart.main(Native Method)
2022-09-16 11:53:08.130   427-1963  ActivityManager         system_process                       W    Force finishing activity sk.baka.photoframe/.MainActivity
2022-09-16 11:53:08.810   427-444   ActivityManager         system_process                       W  Activity pause timeout for ActivityRecord{423e5b88 u0 sk.baka.photoframe/.MainActivity t25 f}
2022-09-16 11:53:08.943   660-660   Timeline                com.cyanogenmod.trebuchet            I  Timeline: Activity_idle id: android.os.BinderProxy@41d1a1b0 time:876343687
2022-09-16 11:53:09.349   427-441   Timeline                system_process                       I  Timeline: Activity_windows_visible id: ActivityRecord{41ea9728 u0 com.cyanogenmod.trebuchet/org.cyanogenmod.trebuchet.CustomHomeLauncher t1} time:876344096
2022-09-16 11:53:10.146   117-117   AudioPolicyManagerBase  pid-117                              D  getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
2022-09-16 11:53:10.146   117-117   AudioPolicyManagerBase  pid-117                              D  getOutput() returns output 2
2022-09-16 11:53:10.146   117-272   AudioPolicyManagerBase  pid-117                              D  getOutput() device 2, stream 1, samplingRate 0, format 0, channelMask 3, flags 0
2022-09-16 11:53:10.146   117-272   AudioPolicyManagerBase  pid-117                              D  getOutput() returns output 2
2022-09-16 11:53:10.146   117-490   AudioPolicyManagerBase  pid-117                              D  getOutput() device 2, stream 1, samplingRate 48000, format 1, channelMask 3, flags 4
2022-09-16 11:53:10.146   117-490   AudioPolicyManagerBase  pid-117                              D  getOutput() returns output 2
2022-09-16 11:53:10.146   427-488   AudioTrack              system_process                       W  AUDIO_OUTPUT_FLAG_FAST denied by client due to mismatching sample rate (48000 vs 44100)
2022-09-16 11:53:10.146   117-117   AudioFlinger            pid-117                              D  start(4099), calling pid 427 session 108
2022-09-16 11:53:10.146   117-117   AudioFlinger            pid-117                              D  ? => ACTIVE (4099) on thread 0x40f3cec8
2022-09-16 11:53:10.146   117-117   AudioPolicyManagerBase  pid-117                              D  startOutput() output 2, stream 1, session 108
2022-09-16 11:53:10.146 23465-23465 Process                 sk.baka.photoframe                   I  Sending signal. PID: 23465 SIG: 9
2022-09-16 11:53:10.161   427-850   InputMetho...gerService system_process                       W  Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@422f4050 attribute=null, token = android.os.BinderProxy@41e25228
2022-09-16 11:53:10.177   427-597   ActivityManager         system_process                       I  Process sk.baka.photoframe (pid 23465) has died.

```

**Comment by asktoby** [comment]
Hopefully I gathered the log correctly.
The device is on Android 4.4.4.4, CyanogenMod 11-20160822-NIGHTLY-p3110. Admittedly rather old but this is why I want to use the device as a photo frame :)

**Comment by mvysny** [comment]
Awesome work, thank you so much! Indeed the source of the problems is visible in the log: `java.lang.VerifyError: sk/baka/android/spi/Java7FS`. That means that Android doesn't like the `Java7FS` class, but it doesn't say why. Let's investigate.

**Comment by mvysny** [comment]
Ah, okay. The Java7FS contains API not present in Android 4.4, and Android thus can't load the class and fails with VerifyError. Just a sec.

**Comment by mvysny** [comment]
> this is why I want to use the device as a photo frame :)

Absolutely - this is exactly the primary use-case which PhotoCloud should support without issues :)

**Comment by mvysny** [comment]
Alrighty, the app is running properly in the Android 4.4 API 19 emulator, so let's mark the bug as fixed. I'll release new PhotoCloud soon.

Fixed in PhotoCloud 1.14.5

**Comment by mvysny** [comment]
Release is under review and should be out soon. Please let me know whether it works properly.

**Comment by asktoby** [comment]
Fantastic support, thank you. It works again!
I've updated my review on the Play store.
Thanks again.
