### ISSUE TITLE
Error adding NextCloud account: java.lang.NumberFormatException

### ISSUE THREAD

**Issue by rgouveia-github** [mvysny/photocloud-frame-slideshow#39]
Hi there!
Thank you for writing PhotoCloud. My idea is to use it as an alternative to Google Photos but I'm having this error when I try to add my account:
`Error: sk.baka.photoframe.util.IOExceptionWithCause: list/ failed: -1: java.lang.NumberFormatException: Invalid long: "null"`

I've troubleshoot it further and it seems that this error comes up when the password is bigger than X characters.
I'm using the auto generated passwords for apps under Nextcloud which are like this: 
`SXamJ-HrA63-saoFr-poitw-g6Rms`

Could you please have a look ?
Thank you.

**Comment by mvysny** [comment]
Hey, thanks for letting me know! Unfortunately I do not have this kind of error reported in my console, so I need a stacktrace of it. Could you obtain one from your phone's log please? You can follow http://aedict.eu/faq.html `Aedict 3 log` tutorial to obtain one. Thanks!

**Comment by mvysny** [comment]
Or try to kill PhotoCloud and start it afresh, as stated here: https://support.crashlytics.com/knowledgebase/articles/202805-logging-caught-exceptions

**Comment by rgouveia-github** [comment]
Thank you for getting back to me.
I've killed PhotoCloud and started it back again but still same issue.

I'll try the log option later but the link you sent me is for a dictionary app ? Not sure how it's related to the log file ?

**Comment by mvysny** [comment]
Yeah, the tutorial is hosted on a dictionary app page, but it's just a general set of instructions on how you can obtain the log from your phone, so you can ignore the dictionary app-specific stuff safely.

**Comment by rgouveia-github** [comment]
Thank you.
Here is the log:
```
09-27 10:13:51.193 10631 10631 I PhotoFrame:DirUtils: DirUtils: using SPI AndroidFS
09-27 10:13:51.267 10631 10631 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Received android.intent.action.ACTION_POWER_CONNECTED
09-27 10:13:51.280 10631 10631 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Power cable connected; startSlideshow=false
09-27 10:13:51.320 10631 10631 I PhotoFrame:InAppPurcha*: onBillingInitialized()
09-27 10:13:51.399 10631 10631 I PhotoFrame:InAppPurcha*: unlock.remote_streams are now NOT PURCHASED
09-27 10:13:51.399 10631 10631 I PhotoFrame:InAppPurcha*: unlock.daydream are now NOT PURCHASED
09-27 10:16:06.052 12015 12015 I PhotoFrame:DirUtils: DirUtils: using SPI AndroidFS
09-27 10:16:06.114 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Received android.intent.action.ACTION_POWER_DISCONNECTED
09-27 10:16:06.132 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Power cable disconnected; stopSlideshow=false
09-27 10:16:06.136 12015 12015 I PhotoFrame:InAppPurcha*: onBillingInitialized()
09-27 10:16:06.253 12015 12015 I PhotoFrame:InAppPurcha*: unlock.remote_streams are now NOT PURCHASED
09-27 10:16:06.253 12015 12015 I PhotoFrame:InAppPurcha*: unlock.daydream are now NOT PURCHASED
09-27 10:16:19.357 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Received android.intent.action.ACTION_POWER_CONNECTED
09-27 10:16:19.357 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Power cable connected; startSlideshow=false
09-27 10:16:28.671 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Received android.intent.action.ACTION_POWER_DISCONNECTED
09-27 10:16:28.672 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Power cable disconnected; stopSlideshow=false
09-27 10:16:33.302 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Received android.intent.action.ACTION_POWER_CONNECTED
09-27 10:16:33.302 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Power cable connected; startSlideshow=false
09-27 10:16:42.927 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Received android.intent.action.ACTION_POWER_DISCONNECTED
09-27 10:16:42.927 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Power cable disconnected; stopSlideshow=false
09-27 10:16:43.240 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Received android.intent.action.ACTION_POWER_CONNECTED
09-27 10:16:43.240 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Power cable connected; startSlideshow=false
09-27 10:16:44.859 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Received android.intent.action.ACTION_POWER_DISCONNECTED
09-27 10:16:44.859 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Power cable disconnected; stopSlideshow=false
09-27 10:16:45.356 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Received android.intent.action.ACTION_POWER_CONNECTED
09-27 10:16:45.356 12015 12015 I PhotoFrame:PowerConnec*: PhotoCloudBoot: Power cable connected; startSlideshow=false
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil: Secure XML processing is not supported
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil: javax.xml.parsers.ParserConfigurationException: http://javax.xml.XMLConstants/feature/secure-processing
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at org.apache.harmony.xml.parsers.DocumentBuilderFactoryImpl.setFeature(DocumentBuilderFactoryImpl.java:101)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at org.apache.jackrabbit.webdav.xml.DomUtil.createFactory(DomUtil.java:71)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at org.apache.jackrabbit.webdav.xml.DomUtil.<clinit>(DomUtil.java:62)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at org.apache.jackrabbit.webdav.client.methods.PropFindMethod.<init>(PropFindMethod.java:82)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at org.apache.jackrabbit.webdav.client.methods.PropFindMethod.<init>(PropFindMethod.java:69)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:77)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:132)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at sk.baka.photoframe.fsimpl.owncloud.OwncloudFileSystem.run(OwncloudFileSystem.kt:60)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at sk.baka.photoframe.fsimpl.owncloud.OwncloudFileSystem.list(OwncloudFileSystem.kt:121)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at sk.baka.photoframe.fsimpl.cache.ThumbnailCache$ThumbnailCacheFileSystem.list(ThumbnailCache.java:132)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at sk.baka.photoframe.fsimpl.owncloud.AddOwncloudActivity$testConnection$1.invoke(AddOwncloudActivity.kt:78)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at sk.baka.photoframe.fsimpl.owncloud.AddOwncloudActivity$testConnection$1.invoke(AddOwncloudActivity.kt:25)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at sk.baka.photoframe.util.android.ViewsKt$asyncWithDialog$2.invoke(Views.kt:159)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at sk.baka.photoframe.util.android.ViewsKt$asyncWithDialog$2.invoke(Views.kt)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:140)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at org.jetbrains.anko.AsyncKt$sam$Callable$761a5578.call(Async.kt)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-27 10:22:19.899 12015 14100 W PhotoFrame:DomUtil:  at java.lang.Thread.run(Thread.java:818)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*: Failed to connect to the OwnCloud
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*: sk.baka.photoframe.util.IOExceptionWithCause: list / failed: -1: java.lang.NumberFormatException: Invalid long: "null"
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at sk.baka.photoframe.fsimpl.owncloud.OwncloudFileSystem.run(OwncloudFileSystem.kt:87)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at sk.baka.photoframe.fsimpl.owncloud.OwncloudFileSystem.list(OwncloudFileSystem.kt:121)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at sk.baka.photoframe.fsimpl.cache.ThumbnailCache$ThumbnailCacheFileSystem.list(ThumbnailCache.java:132)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at sk.baka.photoframe.fsimpl.owncloud.AddOwncloudActivity$testConnection$1.invoke(AddOwncloudActivity.kt:78)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at sk.baka.photoframe.fsimpl.owncloud.AddOwncloudActivity$testConnection$1.invoke(AddOwncloudActivity.kt:25)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at sk.baka.photoframe.util.android.ViewsKt$asyncWithDialog$2.invoke(Views.kt:159)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at sk.baka.photoframe.util.android.ViewsKt$asyncWithDialog$2.invoke(Views.kt)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:140)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at org.jetbrains.anko.AsyncKt$sam$Callable$761a5578.call(Async.kt)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at java.lang.Thread.run(Thread.java:818)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*: Caused by: java.lang.NumberFormatException: Invalid long: "null"
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at java.lang.Long.invalidLong(Long.java:124)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at java.lang.Long.parseLong(Long.java:345)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at java.lang.Long.parseLong(Long.java:321)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at com.owncloud.android.lib.common.network.WebdavEntry.<init>(WebdavEntry.java:90)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.readData(ReadRemoteFolderOperation.java:152)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:86)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:132)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  at sk.baka.photoframe.fsimpl.owncloud.OwncloudFileSystem.run(OwncloudFileSystem.kt:60)
09-27 10:22:20.620 12015 14100 E PhotoFrame:AddOwncloud*:  ... 15 more
```

**Comment by mvysny** [comment]
Awesome, thanks! Yes it's a bug in OwnCloud client. Fixed it, the fix will be present in 1.9.8

**Comment by mvysny** [comment]
1.9.8 is out, please reopen and let me know if the fix is not working for you.

**Comment by rgouveia-github** [comment]
Thank you! I've just confirmed it works and will purchase it as well ;-)

**Comment by mvysny** [comment]
Awesome, glad to hear that! Happy that my blind fix worked for you, and thanks for the support ;)
