### ISSUE TITLE
Dropbox fails with v1 retired

### ISSUE THREAD

**Issue by mvysny** [mvysny/photocloud-frame-slideshow#43]
Dropbox fails with v1 retired

**Comment by mvysny** [comment]
![screenshot_2017-09-29-07-11-27](https://user-images.githubusercontent.com/254091/31000635-c9f5dbaa-a4e5-11e7-9ce8-6d64fa261fad.png)

**Comment by mvysny** [comment]
Lol, official v2 client from Dropbox uses v1 API:
```
Caused by sk.baka.photoframe.util.IOExceptionWithCause: DropboxServerException (nginx): 400 Bad Request (v1_retired)
       at sk.baka.photoframe.fsimpl.dropbox.DropboxFileSystem.list(DropboxFileSystem.kt:64)
       at sk.baka.photoframe.fs.CacheFileSystem.list(CacheFileSystem.java:104)
       at sk.baka.photoframe.fsimpl.cache.ThumbnailCache$ThumbnailCacheFileSystem.list(ThumbnailCache.java:132)
       at sk.baka.photoframe.fs.FilterFileSystem.list(FilterFileSystem.kt:27)
       at sk.baka.photoframe.fs.FilterFileSystem.list(FilterFileSystem.kt:27)
       at sk.baka.photoframe.fs.SortFileSystem.list(SortFileSystem.kt:18)
       at sk.baka.photoframe.stream.SimpleDirTreeFileIterator$ListChildrenRunnable.call(SimpleDirTreeFileIterator.java:313)
       at sk.baka.photoframe.stream.SimpleDirTreeFileIterator$ListChildrenRunnable.call(SimpleDirTreeFileIterator.java:270)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by com.dropbox.client2.exception.DropboxServerException
       at com.dropbox.client2.RESTUtility.parseAsJSON(RESTUtility.java:265)
       at com.dropbox.client2.RESTUtility.execute(RESTUtility.java:415)
       at com.dropbox.client2.RESTUtility.execute(RESTUtility.java:339)
       at com.dropbox.client2.RESTUtility.streamRequest(RESTUtility.java:194)
       at com.dropbox.client2.RESTUtility.request(RESTUtility.java:124)
       at com.dropbox.client2.DropboxAPI.metadata(DropboxAPI.java:1919)
       at sk.baka.photoframe.fsimpl.dropbox.DropboxFileSystem.list(DropboxFileSystem.kt:43)
       at sk.baka.photoframe.fs.CacheFileSystem.list(CacheFileSystem.java:104)
       at sk.baka.photoframe.fsimpl.cache.ThumbnailCache$ThumbnailCacheFileSystem.list(ThumbnailCache.java:132)
       at sk.baka.photoframe.fs.FilterFileSystem.list(FilterFileSystem.kt:27)
       at sk.baka.photoframe.fs.FilterFileSystem.list(FilterFileSystem.kt:27)
       at sk.baka.photoframe.fs.SortFileSystem.list(SortFileSystem.kt:18)
       at sk.baka.photoframe.stream.SimpleDirTreeFileIterator$ListChildrenRunnable.call(SimpleDirTreeFileIterator.java:313)
       at sk.baka.photoframe.stream.SimpleDirTreeFileIterator$ListChildrenRunnable.call(SimpleDirTreeFileIterator.java:270)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:8
```

**Comment by mvysny** [comment]
https://stackoverflow.com/questions/46482543/android-dropbox-client-fails-with-v1-retired

**Comment by CarrotShapedTurtle** [comment]
I'm getting the same Photocloud Error message. Actually I switched to this app from Dayframe + paid the AU$12 (remove the nagging reminder + activate Daydream) to avoid precisely that problem... :(

**Comment by mvysny** [comment]
Oh crap, I'm very sorry about that. I have the new Dropbox API in place, testing.

**Comment by mvysny** [comment]
Fixed in 1.9.9

**Comment by CarrotShapedTurtle** [comment]
Wow, that was fast!
It works now, after removing the Dropbox stream and re-adding it. Thanks!

**Comment by mvysny** [comment]
Thanks! Yeah I suspect that Dropbox will incorrectly report v1 retired or v2 unsupported until you remove the Dropbox stream from  photocloud and add it back again, forcing it to re-authenticate.
