### ISSUE TITLE
Show which stream is unlinked

### ISSUE THREAD

**Issue by mvysny** [mvysny/photocloud-frame-slideshow#62]
Dropbox often becomes unlinked and photocloud tend to crash for the user:
```
Caused by java.lang.IllegalStateException: Dropbox is not linked!
       at sk.baka.photoframe.stream.StreamSource.newFileSystem(StreamSource.kt:274)
       at sk.baka.photoframe.stream.StreamSource.newFileSystem(StreamSource.kt:203)
       at sk.baka.photoframe.stream.StreamSource.newFileSystem$default(StreamSource.kt:202)
       at sk.baka.photoframe.frame.PhotoIterator.createIterator(PhotoIterator.kt:66)
       at sk.baka.photoframe.frame.PhotoIterator.createIterator(PhotoIterator.kt:32)
       at sk.baka.photoframe.frame.PhotoFrameActivity.onCreate(PhotoFrameActivity.kt:108)
       at android.app.Activity.performCreate(Activity.java:5188)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
```

1. Improve unlinked detection on activity launch
2. Show which streams are unlinked in the stream list activity

**Comment by mvysny** [comment]
Fixed in 1.10.7
