### ISSUE TITLE
Failed to parse EXIF

### ISSUE THREAD

**Issue by mvysny** [mvysny/photocloud-frame-slideshow#78]
Sometimes the EXIF is malformed and the entire slideshow stops because of that. Example of such parsing error:

```
Caused by java.lang.NumberFormatException: There are more than one component
       at android.support.media.ExifInterface$ExifAttribute.getIntValue(ExifInterface.java:852)
       at android.support.media.ExifInterface.readImageFileDirectory(ExifInterface.java:3036)
       at android.support.media.ExifInterface.readExifSegment(ExifInterface.java:2791)
       at android.support.media.ExifInterface.getJpegAttributes(ExifInterface.java:2413)
       at android.support.media.ExifInterface.loadAttributes(ExifInterface.java:1765)
       at android.support.media.ExifInterface.<init>(ExifInterface.java:1336)
       at sk.baka.photoframe.fsimpl.cache.CacheBitmapTransformerKt.tryLoadExif(CacheBitmapTransformer.kt:233)
```

**Comment by mvysny** [comment]
Fixed in PhotoCloud 1.11.2
